// 多语言翻译数据
const translations = {
    'en': {
        'nav_home': 'Home',
        'nav_products': 'Golf Bags',
        'nav_custom': 'Custom Solutions',
        'nav_manufacturing': 'Manufacturing',
        'nav_about': 'About Us',
        'nav_blog': 'Blog',
        'nav_contact': 'Contact Us',
        'hero_title': 'Professional Golf Bag Manufacturer',
        'hero_subtitle': 'We provide high-quality custom golf bags and accessories for brands worldwide. OEM/ODM services with competitive pricing and on-time delivery.',
        'hero_cta1': 'Get a Quote',
        'hero_cta2': 'View Products',
        'hero_feature1': '10+ Years Experience',
        'hero_feature2': 'BSCI & ISO9001 Certified',
        'hero_feature3': 'Global Shipping',
        'services_title': 'Our Services',
        'services_desc': 'Comprehensive solutions for your golf bag needs',
        'service1_title': 'Custom Design',
        'service1_desc': 'Tailor-made golf bags according to your specifications',
        'service2_title': 'OEM Manufacturing',
        'service2_desc': 'Private label production with your brand identity',
        'service3_title': 'Quality Control',
        'service3_desc': 'Strict quality standards for every product',
        'service4_title': 'Logistics Support',
        'service4_desc': 'Global shipping and delivery solutions',
        'products_title': 'Featured Products',
        'products_desc': 'Discover our premium golf bag collection',
        'product1_title': 'Tour Series Golf Bag',
        'product1_desc': 'Professional-grade golf bag with premium materials',
        'product2_title': 'Cart Golf Bag',
        'product2_desc': 'Lightweight and durable cart bag with multiple pockets',
        'product3_title': 'Stand Golf Bag',
        'product3_desc': 'Versatile stand bag with ergonomic design',
        'product4_title': 'Travel Golf Bag',
        'product4_desc': 'Protective travel bag for safe transportation',
        'manufacturing_title': 'Manufacturing Capabilities',
        'manufacturing_desc': 'State-of-the-art facilities and advanced production techniques',
        'choose_title': 'Why Choose Us',
        'choose_desc': 'The advantages of partnering with GolfBagFactories',
        'choose1_title': 'Expertise & Experience',
        'choose1_desc': 'Over a decade of specialized golf bag manufacturing',
        'choose2_title': 'Customization Options',
        'choose2_desc': 'Endless possibilities to create unique golf bags',
        'choose3_title': 'Competitive Pricing',
        'choose3_desc': 'Direct factory pricing without intermediaries',
        'choose4_title': 'Timely Delivery',
        'choose4_desc': 'Reliable production schedules and on-time shipping',
        'testimonial_title': 'What Our Clients Say',
        'testimonial1_text': 'The quality of the golf bags exceeded our expectations. The attention to detail and craftsmanship is impressive.',
        'testimonial1_author': 'John Smith, CEO at GolfPro Inc.',
        'testimonial2_text': 'Working with GolfBagFactories has been a game-changer for our brand. Their custom solutions perfectly match our requirements.',
        'testimonial2_author': 'Sarah Johnson, Product Director at ProGolf Co.',
        'testimonial3_text': 'We appreciate the professionalism and reliability of the team. They consistently deliver high-quality products on time.',
        'testimonial3_author': 'Michael Chen, Founder of Ace Golf Brands',
        'cta_title': 'Ready to Start Your Project?',
        'cta_desc': 'Contact us today for a free quote and consultation',
        'footer_about': 'Premium golf bag manufacturing services for brands worldwide. Quality craftsmanship, custom designs, and competitive pricing.',
        'footer_quick_links': 'Quick Links',
        'footer_services': 'Our Services',
        'footer_contact': 'Contact Us',
        'footer_service1': 'Custom Golf Bag Design',
        'footer_service2': 'Private Label Manufacturing',
        'footer_service3': 'Logo & Branding Application',
        'footer_service4': 'Quality Control & Testing',
        'footer_service5': 'Global Shipping & Logistics',
        'footer_service6': 'After-Sales Support',
        'footer_address': '888 Golf Avenue, Sports City, China, 518000',
        'footer_email': 'cco@junyuanbags.com',
        'footer_copyright': '© 2023 GolfBagFactories. All rights reserved.',
        'footer_privacy': 'Privacy Policy',
        'footer_terms': 'Terms of Service',
        'footer_cookie': 'Cookie Policy'
    },
    'es': {
        'nav_home': 'Inicio',
        'nav_products': 'Bolsas de Golf',
        'nav_custom': 'Soluciones Personalizadas',
        'nav_manufacturing': 'Manufactura',
        'nav_about': 'Sobre Nosotros',
        'nav_blog': 'Blog',
        'nav_contact': 'Contáctenos',
        'hero_title': 'Fabricante Profesional de Bolsas de Golf',
        'hero_subtitle': 'Proporcionamos bolsas de golf personalizadas de alta calidad y accesorios para marcas en todo el mundo. Servicios OEM/ODM con precios competitivos y entrega puntual.',
        'hero_cta1': 'Obtener Presupuesto',
        'hero_cta2': 'Ver Productos',
        'hero_feature1': '+10 Años de Experiencia',
        'hero_feature2': 'Certificado BSCI e ISO9001',
        'hero_feature3': 'Envío Global',
        'services_title': 'Nuestros Servicios',
        'services_desc': 'Soluciones integrales para sus necesidades de bolsas de golf',
        'service1_title': 'Diseño Personalizado',
        'service1_desc': 'Bolsas de golf hechas a medida según sus especificaciones',
        'service2_title': 'Manufactura OEM',
        'service2_desc': 'Producción de marca privada con su identidad de marca',
        'service3_title': 'Control de Calidad',
        'service3_desc': 'Estandares de calidad estrictos para cada producto',
        'service4_title': 'Soporte Logístico',
        'service4_desc': 'Soluciones de envío y entrega globales',
        'products_title': 'Productos Destacados',
        'products_desc': 'Descubra nuestra colección premium de bolsas de golf',
        'product1_title': 'Bolsa de Golf Serie Tour',
        'product1_desc': 'Bolsa de golf de grado profesional con materiales premium',
        'product2_title': 'Bolsa de Golf para Carrito',
        'product2_desc': 'Bolsa ligera y duradera para carrito con múltiples bolsillos',
        'product3_title': 'Bolsa de Golf con Soporte',
        'product3_desc': 'Bolsa versátil con soporte y diseño ergonómico',
        'product4_title': 'Bolsa de Golf para Viaje',
        'product4_desc': 'Bolsa protectora para transporte seguro',
        'manufacturing_title': 'Capacidades de Manufactura',
        'manufacturing_desc': 'Instalaciones de última generación y técnicas avanzadas de producción',
        'choose_title': 'Por Qué Elegirnos',
        'choose_desc': 'Las ventajas de asociarse con GolfBagFactories',
        'choose1_title': 'Experiencia y Conocimiento',
        'choose1_desc': 'Más de una década de fabricación especializada de bolsas de golf',
        'choose2_title': 'Opciones de Personalización',
        'choose2_desc': 'Infinitas posibilidades para crear bolsas de golf únicas',
        'choose3_title': 'Precios Competitivos',
        'choose3_desc': 'Precios directos de fábrica sin intermediarios',
        'choose4_title': 'Entrega Puntual',
        'choose4_desc': 'Programas de producción confiables y envío a tiempo',
        'testimonial_title': 'Lo Que Dicen Nuestros Clientes',
        'testimonial1_text': 'La calidad de las bolsas de golf superó nuestras expectativas. La atención al detalle y la artesanía son impresionantes.',
        'testimonial1_author': 'John Smith, CEO en GolfPro Inc.',
        'testimonial2_text': 'Trabajar con GolfBagFactories ha cambiado las reglas del juego para nuestra marca. Sus soluciones personalizadas se adaptan perfectamente a nuestros requisitos.',
        'testimonial2_author': 'Sarah Johnson, Directora de Producto en ProGolf Co.',
        'testimonial3_text': 'Apreciamos el profesionalismo y la fiabilidad del equipo. Consistente en entregar productos de alta calidad a tiempo.',
        'testimonial3_author': 'Michael Chen, Fundador de Ace Golf Brands',
        'cta_title': '¿Listo para Iniciar su Proyecto?',
        'cta_desc': 'Contáctenos hoy para una cotización y consulta gratuitas',
        'footer_about': 'Servicios premium de fabricación de bolsas de golf para marcas en todo el mundo. Artesanía de calidad, diseños personalizados y precios competitivos.',
        'footer_quick_links': 'Enlaces Rápidos',
        'footer_services': 'Nuestros Servicios',
        'footer_contact': 'Contáctenos',
        'footer_service1': 'Diseño Personalizado de Bolsas de Golf',
        'footer_service2': 'Manufactura de Marca Privada',
        'footer_service3': 'Aplicación de Logotipos y Marca',
        'footer_service4': 'Control de Calidad y Pruebas',
        'footer_service5': 'Envío Global y Logística',
        'footer_service6': 'Soporte Post-Venta',
        'footer_address': 'Avenida Golf 888, Ciudad Deportiva, China, 518000',
        'footer_email': 'cco@junyuanbags.com',
        'footer_copyright': '© 2023 GolfBagFactories. Todos los derechos reservados.',
        'footer_privacy': 'Política de Privacidad',
        'footer_terms': 'Términos de Servicio',
        'footer_cookie': 'Política de Cookies'
    },
    'fr': {
        'nav_home': 'Accueil',
        'nav_products': 'Sac de Golf',
        'nav_custom': 'Solutions Personnalisées',
        'nav_manufacturing': 'Fabrication',
        'nav_about': 'À Propos de Nous',
        'nav_blog': 'Blog',
        'nav_contact': 'Contactez-Nous',
        'hero_title': 'Fabricant Professionnel de Sacs de Golf',
        'hero_subtitle': 'Nous proposons des sacs de golf personnalisés de haute qualité et des accessoires pour des marques du monde entier. Services OEM/ODM avec prix compétitifs et livraison à temps.',
        'hero_cta1': 'Obtenir un Devis',
        'hero_cta2': 'Voir les Produits',
        'hero_feature1': '+10 Ans d\'Expérience',
        'hero_feature2': 'Certifié BSCI et ISO9001',
        'hero_feature3': 'Expédition Mondiale',
        'services_title': 'Nos Services',
        'services_desc': 'Solutions complètes pour vos besoins en sacs de golf',
        'service1_title': 'Conception Personnalisée',
        'service1_desc': 'Sacs de golf sur mesure selon vos spécifications',
        'service2_title': 'Fabrication OEM',
        'service2_desc': 'Production de marque privée avec votre identité de marque',
        'service3_title': 'Contrôle de Qualité',
        'service3_desc': 'Normes de qualité strictes pour chaque produit',
        'service4_title': 'Support Logistique',
        'service4_desc': 'Solutions d\'expédition et de livraison mondiales',
        'products_title': 'Produits en Vedette',
        'products_desc': 'Découvrez notre collection premium de sacs de golf',
        'product1_title': 'Sac de Golf Série Tour',
        'product1_desc': 'Sac de golf de qualité professionnelle avec matériaux premium',
        'product2_title': 'Sac de Golf pour Chariot',
        'product2_desc': 'Sac léger et durable pour chariot avec multiples poches',
        'product3_title': 'Sac de Golf à Pied',
        'product3_desc': 'Sac polyvalent avec pieds et design ergonomique',
        'product4_title': 'Sac de Golf de Voyage',
        'product4_desc': 'Sac de protection pour transport sécurisé',
        'manufacturing_title': 'Capacités de Fabrication',
        'manufacturing_desc': 'Installations à la pointe de la technologie et techniques de production avancées',
        'choose_title': 'Pourquoi Nous Choisir',
        'choose_desc': 'Les avantages de travailler avec GolfBagFactories',
        'choose1_title': 'Expertise et Expérience',
        'choose1_desc': 'Plus d\'une décennie de fabrication spécialisée de sacs de golf',
        'choose2_title': 'Options de Personnalisation',
        'choose2_desc': 'Possibilités infinies pour créer des sacs de golf uniques',
        'choose3_title': 'Prix Compétitifs',
        'choose3_desc': 'Prix directs d\'usine sans intermédiaires',
        'choose4_title': 'Livraison Ponctuelle',
        'choose4_desc': 'Calendriers de production fiables et expédition à temps',
        'testimonial_title': 'Ce Que Disent Nos Clients',
        'testimonial1_text': 'La qualité des sacs de golf a dépassé nos attentes. L\'attention aux détails et l\'artisanat sont impressionnants.',
        'testimonial1_author': 'John Smith, PDG de GolfPro Inc.',
        'testimonial2_text': 'Travailler avec GolfBagFactories a changé la donne pour notre marque. Leurs solutions personnalisées répondent parfaitement à nos besoins.',
        'testimonial2_author': 'Sarah Johnson, Directrice Produit de ProGolf Co.',
        'testimonial3_text': 'Nous apprécions le professionnalisme et la fiabilité de l\'équipe. Ils fournissent constamment des produits de haute qualité à temps.',
        'testimonial3_author': 'Michael Chen, Fondateur d\'Ace Golf Brands',
        'cta_title': 'Prêt à Démarrer Votre Projet ?',
        'cta_desc': 'Contactez-nous dès aujourd\'hui pour un devis et une consultation gratuits',
        'footer_about': 'Services premium de fabrication de sacs de golf pour marques du monde entier. Artisanat de qualité, designs personnalisés et prix compétitifs.',
        'footer_quick_links': 'Liens Rapides',
        'footer_services': 'Nos Services',
        'footer_contact': 'Contactez-Nous',
        'footer_service1': 'Conception Personnalisée de Sacs de Golf',
        'footer_service2': 'Fabrication de Marque Privée',
        'footer_service3': 'Application de Logo et de Marque',
        'footer_service4': 'Contrôle de Qualité et Tests',
        'footer_service5': 'Expédition Mondiale et Logistique',
        'footer_service6': 'Support Après-Vente',
        'footer_address': '888 Avenue du Golf, Ville Sportive, Chine, 518000',
        'footer_email': 'cco@junyuanbags.com',
        'footer_copyright': '© 2023 GolfBagFactories. Tous droits réservés.',
        'footer_privacy': 'Politique de Confidentialité',
        'footer_terms': 'Conditions d\'Utilisation',
        'footer_cookie': 'Politique de Cookies'
    },
    'de': {
        'nav_home': 'Startseite',
        'nav_products': 'Golftaschen',
        'nav_custom': 'Individuelle Lösungen',
        'nav_manufacturing': 'Herstellung',
        'nav_about': 'Über Uns',
        'nav_blog': 'Blog',
        'nav_contact': 'Kontakt',
        'hero_title': 'Professioneller Golftaschenhersteller',
        'hero_subtitle': 'Wir bieten hochwertige individuelle Golftaschen und Zubehör für Marken weltweit. OEM/ODM-Dienstleistungen zu wettbewerbsfähigen Preisen und pünktlicher Lieferung.',
        'hero_cta1': 'Kostenloses Angebot anfordern',
        'hero_cta2': 'Produkte anzeigen',
        'hero_feature1': '+10 Jahre Erfahrung',
        'hero_feature2': 'BSCI- und ISO9001-zertifiziert',
        'hero_feature3': 'Weltweiter Versand',
        'services_title': 'Unsere Dienstleistungen',
        'services_desc': 'Umfassende Lösungen für Ihre Golftaschenbedürfnisse',
        'service1_title': 'Individuelles Design',
        'service1_desc': 'Maßgeschneiderte Golftaschen nach Ihren Spezifikationen',
        'service2_title': 'OEM-Herstellung',
        'service2_desc': 'Private-Label-Produktion mit Ihrer Markenidentität',
        'service3_title': 'Qualitätskontrolle',
        'service3_desc': 'Strenge Qualitätsstandards für jedes Produkt',
        'service4_title': 'Logistikunterstützung',
        'service4_desc': 'Globale Versand- und Lieferlösungen',
        'products_title': 'Ausgewählte Produkte',
        'products_desc': 'Entdecken Sie unsere Premium-Golftaschenkollektion',
        'product1_title': 'Tour-Serie Golftasche',
        'product1_desc': 'Professionelle Golftasche aus Premium-Materialien',
        'product2_title': 'Trolley-Golftasche',
        'product2_desc': 'Leichte und langlebige Trolley-Tasche mit mehreren Taschen',
        'product3_title': 'Stand-Golftasche',
        'product3_desc': 'Universelle Standtasche mit ergonomischem Design',
        'product4_title': 'Reise-Golftasche',
        'product4_desc': 'Schutzhülle für sicheren Transport',
        'manufacturing_title': 'Herstellungskapazitäten',
        'manufacturing_desc': 'Modernste Anlagen und fortschrittliche Produktionsverfahren',
        'choose_title': 'Warum Uns Wählen',
        'choose_desc': 'Die Vorteile einer Zusammenarbeit mit GolfBagFactories',
        'choose1_title': 'Expertise und Erfahrung',
        'choose1_desc': 'Über ein Jahrzehnt spezialisierte Golftaschenherstellung',
        'choose2_title': 'Anpassungsmöglichkeiten',
        'choose2_desc': 'Endlose Möglichkeiten zur Schaffung einzigartiger Golftaschen',
        'choose3_title': 'Wettbewerbsfähige Preise',
        'choose3_desc': 'Direkte Fabrikpreise ohne Zwischenhändler',
        'choose4_title': 'Pünktliche Lieferung',
        'choose4_desc': 'Zuverlässige Produktionspläne und pünktlicher Versand',
        'testimonial_title': 'Was Unsere Kunden Sagen',
        'testimonial1_text': 'Die Qualität der Golftaschen hat unsere Erwartungen übertroffen. Die Liebe zum Detail und das Handwerk sind beeindruckend.',
        'testimonial1_author': 'John Smith, CEO bei GolfPro Inc.',
        'testimonial2_text': 'Die Zusammenarbeit mit GolfBagFactories hat für unsere Marke einen Paradigmenwechsel bewirkt. Ihre individuellen Lösungen entsprechen perfekt unseren Anforderungen.',
        'testimonial2_author': 'Sarah Johnson, Produktionsleiterin bei ProGolf Co.',
        'testimonial3_text': 'Wir schätzen das Professionalismus und die Zuverlässigkeit des Teams. Sie liefern konsistent qualitativ hochwertige Produkte pünktlich.',
        'testimonial3_author': 'Michael Chen, Gründer von Ace Golf Brands',
        'cta_title': 'Bereit, Ihr Projekt zu Starten?',
        'cta_desc': 'Kontaktieren Sie uns noch heute für ein kostenloses Angebot und eine Beratung',
        'footer_about': 'Premium-Golftaschenherstellungsdienstleistungen für Marken weltweit. Qualitativ hochwertiges Handwerk, individuelle Designs und wettbewerbsfähige Preise.',
        'footer_quick_links': 'Schnelllinks',
        'footer_services': 'Unsere Dienstleistungen',
        'footer_contact': 'Kontakt',
        'footer_service1': 'Individuelles Golftaschendesign',
        'footer_service2': 'Private-Label-Herstellung',
        'footer_service3': 'Logo- und Markenanwendung',
        'footer_service4': 'Qualitätskontrolle und Tests',
        'footer_service5': 'Globaler Versand und Logistik',
        'footer_service6': 'After-Sales-Support',
        'footer_address': '888 Golf Avenue, Sportstadt, China, 518000',
        'footer_email': 'cco@junyuanbags.com',
        'footer_copyright': '© 2023 GolfBagFactories. Alle Rechte vorbehalten.',
        'footer_privacy': 'Datenschutzrichtlinie',
        'footer_terms': 'Nutzungsbedingungen',
        'footer_cookie': 'Cookie-Richtlinie'
    },
    'zh': {
        'nav_home': '首页',
        'nav_products': '高尔夫球包',
        'nav_custom': '定制解决方案',
        'nav_manufacturing': '生产制造',
        'nav_about': '关于我们',
        'nav_blog': '博客',
        'nav_contact': '联系我们',
        'hero_title': '专业高尔夫球包制造商',
        'hero_subtitle': '我们为全球品牌提供高品质的定制高尔夫球包和配件。具有竞争力的价格和准时交付的OEM/ODM服务。',
        'hero_cta1': '获取报价',
        'hero_cta2': '查看产品',
        'hero_feature1': '10+年经验',
        'hero_feature2': 'BSCI和ISO9001认证',
        'hero_feature3': '全球配送',
        'services_title': '我们的服务',
        'services_desc': '满足您高尔夫球包需求的综合解决方案',
        'service1_title': '定制设计',
        'service1_desc': '根据您的规格量身定制高尔夫球包',
        'service2_title': 'OEM制造',
        'service2_desc': '带有您品牌标识的自有品牌生产',
        'service3_title': '质量控制',
        'service3_desc': '每个产品严格的质量标准',
        'service4_title': '物流支持',
        'service4_desc': '全球运输和交付解决方案',
        'products_title': '精选产品',
        'products_desc': '探索我们的高端高尔夫球包系列',
        'product1_title': '巡回赛系列高尔夫球包',
        'product1_desc': '采用优质材料的专业级高尔夫球包',
        'product2_title': '球车高尔夫球包',
        'product2_desc': '轻便耐用的球车包，多个口袋',
        'product3_title': '支架高尔夫球包',
        'product3_desc': '具有人体工程学设计的多功能支架包',
        'product4_title': '旅行高尔夫球包',
        'product4_desc': '用于安全运输的保护旅行包',
        'manufacturing_title': '制造能力',
        'manufacturing_desc': '最先进的设施和先进的生产技术',
        'choose_title': '为什么选择我们',
        'choose_desc': '与GolfBagFactories合作的优势',
        'choose1_title': '专业知识与经验',
        'choose1_desc': '十多年专业高尔夫球包制造经验',
        'choose2_title': '定制选项',
        'choose2_desc': '创造独特高尔夫球包的无限可能',
        'choose3_title': '具有竞争力的价格',
        'choose3_desc': '没有中间商的直接工厂价格',
        'choose4_title': '及时交付',
        'choose4_desc': '可靠的生产计划和准时发货',
        'testimonial_title': '客户评价',
        'testimonial1_text': '高尔夫球包的质量超出了我们的期望。对细节的关注和工艺令人印象深刻。',
        'testimonial1_author': 'John Smith，GolfPro Inc.首席执行官',
        'testimonial2_text': '与GolfBagFactories合作彻底改变了我们的品牌。他们的定制解决方案完美匹配我们的要求。',
        'testimonial2_author': 'Sarah Johnson，ProGolf Co.产品总监',
        'testimonial3_text': '我们欣赏团队的专业精神和可靠性。他们始终按时交付高质量的产品。',
        'testimonial3_author': 'Michael Chen，Ace Golf Brands创始人',
        'cta_title': '准备好开始您的项目了吗？',
        'cta_desc': '立即联系我们获取免费报价和咨询',
        'footer_about': '为全球品牌提供高端高尔夫球包制造服务。优质工艺、定制设计和具有竞争力的价格。',
        'footer_quick_links': '快速链接',
        'footer_services': '我们的服务',
        'footer_contact': '联系我们',
        'footer_service1': '定制高尔夫球包设计',
        'footer_service2': '自有品牌制造',
        'footer_service3': '标志和品牌应用',
        'footer_service4': '质量控制和测试',
        'footer_service5': '全球运输和物流',
        'footer_service6': '售后支持',
        'footer_address': '中国体育城高尔夫大道888号，518000',
        'footer_email': 'cco@junyuanbags.com',
        'footer_copyright': '© 2023 GolfBagFactories。保留所有权利。',
        'footer_privacy': '隐私政策',
        'footer_terms': '服务条款',
        'footer_cookie': 'Cookie政策'
    },
    'ja': {
        'nav_home': 'ホーム',
        'nav_products': 'ゴルフバッグ',
        'nav_custom': 'カスタムソリューション',
        'nav_manufacturing': '製造',
        'nav_about': '会社概要',
        'nav_blog': 'ブログ',
        'nav_contact': 'お問い合わせ',
        'hero_title': 'プロフェッショナルゴルフバッグメーカー',
        'hero_subtitle': '世界中のブランドに高品質なカスタムゴルフバッグとアクセサリーを提供しています。競争力のある価格と時間通りの納品を実現するOEM/ODMサービス。',
        'hero_cta1': '見積もりを取得',
        'hero_cta2': '製品を見る',
        'hero_feature1': '10年以上の経験',
        'hero_feature2': 'BSCI・ISO9001認証取得',
        'hero_feature3': 'グローバル配送',
        'services_title': '当社のサービス',
        'services_desc': 'ゴルフバッグのニーズに合わせた包括的なソリューション',
        'service1_title': 'カスタムデザイン',
        'service1_desc': 'お客様の仕様に合わせたオーダーメイドゴルフバッグ',
        'service2_title': 'OEM製造',
        'service2_desc': 'ブランドアイデンティティを備えたプライベートラベル生産',
        'service3_title': '品質管理',
        'service3_desc': '全製品に対する厳格な品質基準',
        'service4_title': '物流サポート',
        'service4_desc': 'グローバルな輸送・配送ソリューション',
        'products_title': '注目製品',
        'products_desc': 'プレミアムゴルフバッグコレクションをご覧ください',
        'product1_title': 'ツアーシリーズゴルフバッグ',
        'product1_desc': 'プレミアム素材を使用したプロ仕様のゴルフバッグ',
        'product2_title': 'カートゴルフバッグ',
        'product2_desc': '複数のポケットを備えた軽量で耐久性のあるカートバッグ',
        'product3_title': 'スタンドゴルフバッグ',
        'product3_desc': '人間工学的デザインを採用した多目的スタンドバッグ',
        'product4_title': 'トラベルゴルフバッグ',
        'product4_desc': '安全な輸送のための保護用トラベルバッグ',
        'manufacturing_title': '製造能力',
        'manufacturing_desc': '最新鋭の施設と高度な生産技術',
        'choose_title': 'なぜ私たちを選ぶのか',
        'choose_desc': 'GolfBagFactoriesとのパートナーシップの利点',
        'choose1_title': '専門知識と経験',
        'choose1_desc': '10年以上の専門的なゴルフバッグ製造',
        'choose2_title': 'カスタマイズオプション',
        'choose2_desc': 'ユニークなゴルフバッグを作るための無限の可能性',
        'choose3_title': '競争力のある価格',
        'choose3_desc': '仲介者なしの直接工場価格',
        'choose4_title': 'タイムリーな納品',
        'choose4_desc': '信頼性の高い生産スケジュールと時間通りの出荷',
        'testimonial_title': '顧客の声',
        'testimonial1_text': 'ゴルフバッグの品質は私たちの期待を上回りました。細部への注意と工芸は印象的です。',
        'testimonial1_author': 'John Smith、GolfPro Inc. CEO',
        'testimonial2_text': 'GolfBagFactoriesとの協力は私たちのブランドに革新をもたらしました。彼らのカスタムソリューションは私たちの要件に完全に合致しています。',
        'testimonial2_author': 'Sarah Johnson、ProGolf Co. 製品ディレクター',
        'testimonial3_text': '私たちはチームのプロフェッショナリズムと信頼性を高く評価しています。彼らは一貫して高品質な製品を時間通りに提供しています。',
        'testimonial3_author': 'Michael Chen、Ace Golf Brands 創設者',
        'cta_title': 'あなたのプロジェクトを始める準備はできていますか？',
        'cta_desc': '無料の見積もりとコンサルティングのために今日私たちに連絡してください',
        'footer_about': '世界中のブランド向けのプレミアムゴルフバッグ製造サービス。高品質な工芸、カスタムデザイン、競争力のある価格。',
        'footer_quick_links': 'クイックリンク',
        'footer_services': '当社のサービス',
        'footer_contact': 'お問い合わせ',
        'footer_service1': 'カスタムゴルフバッグデザイン',
        'footer_service2': 'プライベートラベル製造',
        'footer_service3': 'ロゴ・ブランド適用',
        'footer_service4': '品質管理・テスト',
        'footer_service5': 'グローバル輸送・物流',
        'footer_service6': 'アフターサービス',
        'footer_address': '中国、体育市、ゴルフアベニュー888番地、518000',
        'footer_email': 'cco@junyuanbags.com',
        'footer_copyright': '© 2023 GolfBagFactories。全著作権所有。',
        'footer_privacy': 'プライバシーポリシー',
        'footer_terms': '利用規約',
        'footer_cookie': 'クッキーポリシー'
    },
    'pt': {
        'nav_home': 'Início',
        'nav_products': 'Bolsas de Golfe',
        'nav_custom': 'Soluções Personalizadas',
        'nav_manufacturing': 'Fabricação',
        'nav_about': 'Sobre Nós',
        'nav_blog': 'Blog',
        'nav_contact': 'Contate-Nos',
        'hero_title': 'Fabricante Profissional de Bolsas de Golfe',
        'hero_subtitle': 'Oferecemos bolsas de golfe personalizadas de alta qualidade e acessórios para marcas em todo o mundo. Serviços OEM/ODM com preços competitivos e entrega pontual.',
        'hero_cta1': 'Solicitar Orçamento',
        'hero_cta2': 'Ver Produtos',
        'hero_feature1': '+10 Anos de Experiência',
        'hero_feature2': 'Certificado BSCI e ISO9001',
        'hero_feature3': 'Envio Global',
        'services_title': 'Nossos Serviços',
        'services_desc': 'Soluções abrangentes para suas necessidades de bolsas de golfe',
        'service1_title': 'Design Personalizado',
        'service1_desc': 'Bolsas de golfe sob medida de acordo com suas especificações',
        'service2_title': 'Fabricação OEM',
        'service2_desc': 'Produção de marca privada com sua identidade de marca',
        'service3_title': 'Controle de Qualidade',
        'service3_desc': 'Padrões de qualidade rigorosos para cada produto',
        'service4_title': 'Suporte Logístico',
        'service4_desc': 'Soluções de envio e entrega globais',
        'products_title': 'Produtos em Destaque',
        'products_desc': 'Descubra nossa coleção premium de bolsas de golfe',
        'product1_title': 'Bolsa de Golfe Série Tour',
        'product1_desc': 'Bolsa de golfe de nível profissional com materiais premium',
        'product2_title': 'Bolsa de Golfe para Carrinho',
        'product2_desc': 'Bolsa leve e durável para carrinho com vários bolsos',
        'product3_title': 'Bolsa de Golfe com Suporte',
        'product3_desc': 'Bolsa versátil com suporte e design ergonômico',
        'product4_title': 'Bolsa de Golfe para Viagem',
        'product4_desc': 'Bolsa protetora para transporte seguro',
        'manufacturing_title': 'Capacidades de Fabricação',
        'manufacturing_desc': 'Instalações de ponta e técnicas avançadas de produção',
        'choose_title': 'Por Que nos Escolher',
        'choose_desc': 'As vantagens de se associar à GolfBagFactories',
        'choose1_title': 'Expertise e Experiência',
        'choose1_desc': 'Mais de uma década de fabricação especializada de bolsas de golfe',
        'choose2_title': 'Opções de Personalização',
        'choose2_desc': 'Possibilidades infinitas para criar bolsas de golfe únicas',
        'choose3_title': 'Preços Competitivos',
        'choose3_desc': 'Preços diretos de fábrica sem intermediários',
        'choose4_title': 'Entrega Pontual',
        'choose4_desc': 'Cronogramas de produção confiáveis e envio pontual',
        'testimonial_title': 'O Que Nossos Clientes Dizem',
        'testimonial1_text': 'A qualidade das bolsas de golfe superou nossas expectativas. A atenção aos detalhes e a artesanato são impressionantes.',
        'testimonial1_author': 'John Smith, CEO da GolfPro Inc.',
        'testimonial2_text': 'Trabalhar com a GolfBagFactories mudou as regras do jogo para nossa marca. Suas soluções personalizadas atendem perfeitamente aos nossos requisitos.',
        'testimonial2_author': 'Sarah Johnson, Diretora de Produtos da ProGolf Co.',
        'testimonial3_text': 'Apreciamos o profissionalismo e a confiabilidade da equipe. Eles entregam consistentemente produtos de alta qualidade pontualmente.',
        'testimonial3_author': 'Michael Chen, Fundador da Ace Golf Brands',
        'cta_title': 'Pronto para Iniciar Seu Projeto?',
        'cta_desc': 'Contate-nos hoje para um orçamento e consulta gratuitos',
        'footer_about': 'Serviços premium de fabricação de bolsas de golfe para marcas em todo o mundo. Artesanato de qualidade, designs personalizados e preços competitivos.',
        'footer_quick_links': 'Links Rápidos',
        'footer_services': 'Nossos Serviços',
        'footer_contact': 'Contate-Nos',
        'footer_service1': 'Design Personalizado de Bolsas de Golfe',
        'footer_service2': 'Fabricação de Marca Privada',
        'footer_service3': 'Aplicação de Logotipo e Marca',
        'footer_service4': 'Controle de Qualidade e Testes',
        'footer_service5': 'Envio Global e Logística',
        'footer_service6': 'Suporte Pós-Venda',
        'footer_address': 'Avenida Golf 888, Cidade Esportiva, China, 518000',
        'footer_email': 'cco@junyuanbags.com',
        'footer_copyright': '© 2023 GolfBagFactories. Todos os direitos reservados.',
        'footer_privacy': 'Política de Privacidade',
        'footer_terms': 'Termos de Serviço',
        'footer_cookie': 'Política de Cookies'
    },
    'ru': {
        'nav_home': 'Главная',
        'nav_products': 'Гольф-сумки',
        'nav_custom': 'Индивидуальные решения',
        'nav_manufacturing': 'Производство',
        'nav_about': 'О нас',
        'nav_blog': 'Блог',
        'nav_contact': 'Связаться с нами',
        'hero_title': 'Профессиональный производитель гольф-сумок',
        'hero_subtitle': 'Мы предлагаем высококачественные индивидуальные гольф-сумки и аксессуары для брендов по всему миру. Услуги OEM/ODM по конкурентным ценам и с доставкой в срок.',
        'hero_cta1': 'Получить предложение',
        'hero_cta2': 'Посмотреть продукты',
        'hero_feature1': '+10 лет опыта',
        'hero_feature2': 'Сертифицировано BSCI и ISO9001',
        'hero_feature3': 'Мировая доставка',
        'services_title': 'Наши услуги',
        'services_desc': 'Комплексные решения для ваших потребностей в гольф-сумках',
        'service1_title': 'Индивидуальный дизайн',
        'service1_desc': 'Гольф-сумки по заказу в соответствии с вашими требованиями',
        'service2_title': 'Производство OEM',
        'service2_desc': 'Производство под собственной маркой с вашей брендовой идентичностью',
        'service3_title': 'Контроль качества',
        'service3_desc': 'Строгие стандарты качества для каждого продукта',
        'service4_title': 'Логистическая поддержка',
        'service4_desc': 'Глобальные решения по доставке и распределению',
        'products_title': 'Популярные продукты',
        'products_desc': 'Ознакомьтесь с нашей премиальной коллекцией гольф-сумок',
        'product1_title': 'Гольф-сумка серии Тур',
        'product1_desc': 'Профессиональная гольф-сумка из премиальных материалов',
        'product2_title': 'Гольф-сумка для тележки',
        'product2_desc': 'Легкая и прочная тележная сумка с несколькими карманами',
        'product3_title': 'Гольф-сумка со стойкой',
        'product3_desc': 'Универсальная сумка со стойкой с эргономичным дизайном',
        'product4_title': 'Гольф-сумка для путешествий',
        'product4_desc': 'Защитная сумка для безопасной перевозки',
        'manufacturing_title': 'Производственные возможности',
        'manufacturing_desc': 'Современные мощности и передовые технологии производства',
        'choose_title': 'Почему выбирают нас',
        'choose_desc': 'Преимущества сотрудничества с GolfBagFactories',
        'choose1_title': 'Экспертиза и опыт',
        'choose1_desc': 'Более десяти лет специализированного производства гольф-сумок',
        'choose2_title': 'Варианты индивидуализации',
        'choose2_desc': 'Бесконечные возможности создания уникальных гольф-сумок',
        'choose3_title': 'Конкурентные цены',
        'choose3_desc': 'Прямые заводские цены без посредников',
        'choose4_title': 'Своевременная доставка',
        'choose4_desc': 'Надежные производственные расписания и своевременная отправка',
        'testimonial_title': 'Отзывы наших клиентов',
        'testimonial1_text': 'Качество гольф-сумок превзошло наши ожидания. Внимание к деталям и мастерство поражают.',
        'testimonial1_author': 'Джон Смит, CEO компании GolfPro Inc.',
        'testimonial2_text': 'Сотрудничество с GolfBagFactories стало переломным моментом для нашего бренда. Их индивидуальные решения идеально соответствуют нашим требованиям.',
        'testimonial2_author': 'Сара Джонсон, директор по продуктам ProGolf Co.',
        'testimonial3_text': 'Мы ценим профессионализм и надежность команды. Они постоянно доставляют высококачественные продукты в срок.',
        'testimonial3_author': 'Майкл Чен, основатель Ace Golf Brands',
        'cta_title': 'Готовы начать свой проект?',
        'cta_desc': 'Свяжитесь с нами сегодня для получения бесплатного предложения и консультации',
        'footer_about': 'Премиальные услуги по производству гольф-сумок для брендов по всему миру. Качественное мастерство, индивидуальные дизайны и конкурентные цены.',
        'footer_quick_links': 'Быстрые ссылки',
        'footer_services': 'Наши услуги',
        'footer_contact': 'Связаться с нами',
        'footer_service1': 'Индивидуальный дизайн гольф-сумок',
        'footer_service2': 'Производство под собственной маркой',
        'footer_service3': 'Нанесение логотипов и брендирование',
        'footer_service4': 'Контроль качества и тестирование',
        'footer_service5': 'Мировая доставка и логистика',
        'footer_service6': 'Послепродажное обслуживание',
        'footer_address': 'Улица Гольф 888, Спортивный город, Китай, 518000',
        'footer_email': 'cco@junyuanbags.com',
        'footer_copyright': '© 2023 GolfBagFactories. Все права защищены.',
        'footer_privacy': 'Политика конфиденциальности',
        'footer_terms': 'Условия обслуживания',
        'footer_cookie': 'Политика cookie'
    }
};